-- VLDTN_ERR_MSG_FRWK_INSERT_PATIENT_SEARCH_ERRORS
INSERT INTO REMISPRD.VLDTN_ERR_MSG_FRWK ( ERR_CD, ERR_MSG, WRNG_SW, ACTV_SW, CREAT_TIME, UPDT_TIME ) 
VALUES( '100000', 'Enter valid date in MM/DD/YYYY format.', 0, 1, SYSTIMESTAMP, SYSTIMESTAMP );